FROM mysql/mysql-server:8.0.18

#COPY ./mysqlconfig/mysql1/my.cnf /etc/mysql/my.cnf

#RUN ["chmod", "644", "/etc/mysql/my.cnf"]

#RUN cd /etc/mysql && touch mysql_error.log && chmod 666 mysql_error.log

#RUN cd /etc/mysql && touch mysql.log && chmod 666 mysql.log