version: "3.8"

services:
  login_mysql:
    build: 
      context: ../Login
      dockerfile: ./docker/DockerFile
    container_name: login_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
     ./mysql.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 5306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
    volumes:
      - ./Login_mysqldata:/var/lib/mysql
    networks:
      - Loginnet

  login1:
    build: 
      context: ../Login
      dockerfile: Dockerfile
    container_name: Login1
    ports: 
      - 8000:3033
    expose:
      # Opens port 3000 on the container
      - 3000
    volumes: 
      - ./:/app
      - "/app/node_modules"
    networks:
      - Loginnet

networks:
  Loginnet:
    driver: bridge